
services:

  mysql:
    container_name: happyschool-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'happyschool'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '123456'

    ports:
      - '3306:3306'
    volumes:
      - happyschool-database-mysql:/var/lib/mysql
    networks:
      - happyschool-network

  happyschool-service:
    container_name: happyschool-service
    build: .
    restart: no
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - '9090:9090'
    depends_on:
      - mysql
    networks:
      - happyschool-network

volumes:
  happyschool-database-mysql:
      name: happyschool-database-mysql

networks:
  happyschool-network:
    name: happyschool-network
    driver: bridge
