server.port=8085
spring.application.name=happyschool

#spring.profiles.active=development
spring.devtools.add-properties=true

#spring.datasource.url=jdbc:mysql://localhost:3306/happyschool?useSSL=false&serverTimezone=UTC
#spring.datasource.username=admin
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.javax.persistence.validation.mode=none

spring.thymeleaf.cache=false

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %yellow(%logger{15}) - %msg%n}

spring.logging.level.org.springframework.web=DEBUG
spring.logging.level.org.hibernate.SQL=DEBUG
spring.logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG
spring.logging.level.com.marcusvbrangel.happyschool=DEBUG

debug: false
