
server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/happyschool?allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=1234

SPRING_APPLICATION_NAME=happyschool
spring.devtools.add-properties=true
spring.thymeleaf.cache=false
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#jakarta.persistence.validation.mode=none
spring.jpa.properties.javax.persistence.validation.mode=none
logging.level.root=INFO
spring.logging.level.org.springframework.web=INFO
spring.logging.level.com.marcusvbrangel.happyschool=INFO
logging.level.com.marcusvbrangel.happyschool.aspects=ERROR
management.endpoints.web.base-path=/happyschool/actuator
management.endpoints.web.exposure.include=*
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %yellow(%logger{15}) - %msg%n}
#spring.output.ansi.enabled=ALWAYS
debub: false



happyschool.pageSize=20
happyschool.contact.pageSize=5
happyschool.contact.successMsg=Your message is submitted successfully.
happyschool.branches[0]=NewYork
happyschool.branches[1]=Delhi
happyschool.branches[2]=Paris
happyschool.branches[3]=Singapore

happyschool.rabbitmq.payment.process.queue=dev.payment.process.v1.queue


#-----------------------------------
#application.environment=DEVELOPMENT
#application.service.quantity=4
#application.service.name=fox
#application.service.active=true








