
name: Java CI with Maven

on:
  pull_request:
    branches:
      - "development"
      - "main"

  workflow_dispatch:

jobs:

  build:
    name: Build and Test with Maven
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: $2a$10$7xVSaCEAYhyAXJ6FD/cqZebaRApVeWD50SRs/kdFBprfCPtJtdKQi
          MYSQL_DATABASE: happyschool
          MYSQL_USER: admin          
          MYSQL_PASSWORD: 1234 
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=15s
          --health-timeout=40s
          --health-retries=100

    steps:
    
    - uses: actions/checkout@v4

    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Wait for MySQL to be healthy
      run: |
        for i in `seq 1 30`; do
          if mysqladmin ping -h "127.0.0.1" --silent; then
            echo "MySQL is up and running"
            break
          fi
          echo "Waiting for MySQL to be up... ($i)"
          sleep 2
        done    

    - name: Build
      run: mvn clean package -Dmaven.test.skip=true
      
    - name: Test
      run: mvn test

    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_HUB_USERNAME }}/happyshool:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ env.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push ${{ env.DOCKER_HUB_USERNAME }}/happyshool:latest







#    - name: Build and Test with Maven
#      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

# 1. implement login on docker hub
# 2. implement push to docker hub
# 3. implement linting
# 4. implement static code analysis
# 5. implement code coverage
# 6. implement security scanning
# 7. implement secret scanning on Dockerfile
# 8. implement a hash code for each sufix image
# 9. escanear imagem docker
# 10. assinar imagem docker
# 11. implement push to aws ecr
# 12. implementar tag relacionadas aos jobs executados
